name: CI Workflow

on:
  pull_request:
    branches: [ main ] # Or any other branch you want to target

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Or the version you use

    - name: Install NPM dependencies
      run: npm install

    - name: Run NPM tests
      run: npm test

    - name: Run CDK Synth
      run: npx cdk synth

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6' # Or the version you use

    # Add any other steps you might need, like deploying to AWS
