name: TESTAPI CI Workflow

on:
  pull_request:
    branches: [ main ] # Or any other branch you want to target

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Or the version you use

    - name: Install NPM dependencies
      working-directory: ./infra
      run: npm install

    - name: Run NPM tests
      working-directory: ./infra
      run: npm test

    - name: Run CDK Synth
      working-directory: ./infra
      run: npx cdk synth

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6' # Or the version you use

    - name: Build .NET Project
      working-directory: ./apps/TestAPI
      run: dotnet build --configuration Release

    - name: Publish .NET Project
      working-directory: ./apps/TestAPI
      run: dotnet publish -c Release
